### ISSUE TITLE
About track2 testing

### ISSUE THREAD

**Issue by AntonioDeFalco** [ipl-uw/2019-CVPR-AIC-Track-2-UWIPL#1]
Using the required libraries versions and following the Readme for dataset pre-processing when I run the test of ReID for the Track2 using your pre-trained model, after several attempts, I always get results close to 0 as shown in the attached testing output.

![OutputVideoReID](https://user-images.githubusercontent.com/11536289/66254039-0ef88700-e771-11e9-98fe-71313af47787.png)

**Comment by tsungweihuang** [comment]
Hi AntonioDeFalco,

It is because of the splitting of the dataset. The current splitting train(333)/query(1052)/gallery(798) is for the AI City Challenge. Because we do not known the car IDs in query/gallery, the output mAP shown above is meaningless. To calculate the actual mAP, you need to upload the output text file (which is in this format: https://www.aicitychallenge.org/2019-data-sets/) to the AI City Challenge evaluation server.
Optionally, you can split the train set into train/query/gallery so that you can evaluate on the known car IDs, and the mAP will be correct.
